pipeline:
  build:
    commands:
      - docker build -t registry.cn-hangzhou.aliyuncs.com/document/document-server:0.0.1 .
  publish:
    image: registry.cn-hangzhou.aliyuncs.com/document/document-server:0.0.1
    username: mojozjd
    password: aliyun_183