workspace:
  base: /go
  path: src/github.com/document-server

pipeline:
#  backend:
#    image: registry.cn-hangzhou.aliyuncs.com/libaray/golang:1.8
#    commands:
#      - go build
#      - go test
  build-image:
      image: plugins/docker
      dockerfile: Dockerfile
      repo: registry.cn-hangzhou.aliyuncs.com/document/document-server
      registry: registry.cn-hangzhou.aliyuncs.com
      username: mojozjd
      password: docker_183
#      secrets: [ docker_username, docker_password ]
      tags: latest