workspace:
  base: /go
  path: src/github.com/mojo-zd/document-server

pipeline:
  backend:
    image: golang
    commands:
      - go build
      - go test
  docker:
      image: plugins/docker
      dockerfile: Dockerfile
      repo: registry.cn-hangzhou.aliyuncs.com/document/document-server
      registry: registry.cn-hangzhou.aliyuncs.com
      username: mojozjd
      password: docker_183